version: '3'
services:
  web:
    build: .
    command: 'python -u app.py'
    ports:
      - '5000:5000'
    environment:
      PYTHONUNBUFFERED: 0
      DB_NAME: 'zoo'
      COLLECTION_NAME: 'monkeys'
      DB_HOST: 'mongo'
      HOST_IP: '0.0.0.0'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
